# Generated by Django 6.0 on 2026-02-03 06:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pathname', models.CharField(max_length=1024, unique=True)),
                ('blob_url', models.URLField()),
                ('download_url', models.URLField(blank=True, null=True)),
                ('content_type', models.CharField(default='text/javascript', max_length=100)),
                ('file_size', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Script',
                'verbose_name_plural': 'Scripts',
                'db_table': 'scripts',
                'ordering': ['-uploaded_at', '-updated_at'],
                'indexes': [models.Index(fields=['owner', 'pathname'], name='scripts_owner_i_0a34c0_idx')],
            },
        ),
    ]
