# Generated by Django 6.0 on 2026-04-23 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='pathname',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterUniqueTogether(
            name='script',
            unique_together={('owner', 'pathname')},
        ),
    ]
