# Generated by Django 5.2.13 on 2026-07-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0003_alter_script_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='is_library',
            field=models.BooleanField(default=False),
        ),
    ]
