# Generated by Django 6.0 on 2026-03-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution_engine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scriptexecution',
            name='logs',
        ),
        migrations.RemoveField(
            model_name='scriptexecution',
            name='stderr',
        ),
        migrations.RemoveField(
            model_name='scriptexecution',
            name='stdout',
        ),
        migrations.AddField(
            model_name='scriptexecution',
            name='logs_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scriptexecution',
            name='stderr_log_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scriptexecution',
            name='stdout_log_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
