# Generated by Django 6.0 on 2026-04-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution_engine', '0003_workflowrun_workflownoderun_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowrun',
            name='credential_id',
        ),
        migrations.RemoveField(
            model_name='workflowrun',
            name='server_id',
        ),
        migrations.RemoveField(
            model_name='workflowrun',
            name='vault_id',
        ),
        migrations.AddField(
            model_name='workflownoderun',
            name='credential_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflownoderun',
            name='server_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflownoderun',
            name='vault_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
