# Generated by Django 6.0 on 2026-04-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution_engine', '0004_remove_workflowrun_credential_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownoderun',
            name='script_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
