# Generated by Django 6.0 on 2026-04-23 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution_engine', '0005_alter_workflownoderun_script_id'),
        ('scripts', '0002_alter_script_pathname_alter_script_unique_together'),
        ('vault', '0008_alter_credential_key_passphrase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptexecution',
            name='credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='vault.credential'),
        ),
        migrations.AlterField(
            model_name='scriptexecution',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='scripts.script'),
        ),
        migrations.AlterField(
            model_name='scriptexecution',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='vault.server'),
        ),
        migrations.AlterField(
            model_name='scriptexecution',
            name='vault',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='vault.vault'),
        ),
        migrations.AlterField(
            model_name='workflownoderun',
            name='script_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='workflownoderun',
            index=models.Index(fields=['script_id'], name='workflow_no_script__7b53d2_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownoderun',
            index=models.Index(fields=['vault_id'], name='workflow_no_vault_i_09b123_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownoderun',
            index=models.Index(fields=['server_id'], name='workflow_no_server__bc7965_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownoderun',
            index=models.Index(fields=['credential_id'], name='workflow_no_credent_d335b9_idx'),
        ),
    ]
