# Generated by Django 5.2.13 on 2026-04-30 17:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution_engine', '0007_workflowrun_notification_email_workflowrun_send_email'),
        ('workflows', '0005_workflow_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrun',
            name='trigger_node_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='trigger_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('http', 'HTTP'), ('schedule', 'Schedule')], default='manual', max_length=20),
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['trigger_source', 'created_at'], name='workflow_ru_trigger_bf4447_idx'),
        ),
    ]
