# Generated by Django 5.2.13 on 2026-06-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution_engine', '0008_add_trigger_source_to_workflowrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowrun',
            name='trigger_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('http', 'HTTP'), ('schedule', 'Schedule'), ('autobot', 'Autobot')], default='manual', max_length=20),
        ),
    ]
