# Generated by Django 5.2.13 on 2026-06-05 04:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution_engine', '0009_alter_workflowrun_trigger_source'),
        ('workflows', '0005_workflow_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRunIdempotencyKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_run_idempotency_keys', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_idempotency_keys', to='workflows.workflow')),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='execution_engine.workflowrun')),
            ],
            options={
                'verbose_name': 'Workflow Run Idempotency Key',
                'verbose_name_plural': 'Workflow Run Idempotency Keys',
                'db_table': 'workflow_run_idempotency_keys',
                'indexes': [models.Index(fields=['created_at'], name='wf_run_idem_created_idx')],
                'unique_together': {('user', 'workflow', 'key')},
            },
        ),
    ]
