# Generated by Django 6.0 on 2026-04-29 11:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('execution_engine', '0007_workflowrun_notification_email_workflowrun_send_email'),
        ('workflows', '0005_workflow_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HttpTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.CharField(max_length=255)),
                ('trigger_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('secret_hash', models.CharField(max_length=255)),
                ('secret_last4', models.CharField(blank=True, max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='http_triggers', to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'HTTP Trigger',
                'verbose_name_plural': 'HTTP Triggers',
                'db_table': 'http_triggers',
                'unique_together': {('workflow', 'node_id')},
            },
        ),
        migrations.CreateModel(
            name='HttpTriggerIdempotencyKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to='triggers.httptrigger')),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='execution_engine.workflowrun')),
            ],
            options={
                'db_table': 'http_trigger_idempotency_keys',
                'indexes': [models.Index(fields=['created_at'], name='http_trig_idem_created_idx')],
                'unique_together': {('trigger', 'key')},
            },
        ),
    ]
