# Generated by Django 5.2.13 on 2026-04-30 17:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution_engine', '0008_add_trigger_source_to_workflowrun'),
        ('triggers', '0001_initial'),
        ('workflows', '0005_workflow_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.CharField(max_length=255)),
                ('cron_expression', models.CharField(max_length=255)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('periodic_task_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='execution_engine.workflowrun')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_triggers', to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'Schedule Trigger',
                'verbose_name_plural': 'Schedule Triggers',
                'db_table': 'schedule_triggers',
                'unique_together': {('workflow', 'node_id')},
            },
        ),
    ]
