# Generated by Django 5.2.13 on 2026-04-30 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0002_add_schedule_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduletrigger',
            name='enabled',
        ),
        migrations.AddField(
            model_name='httptrigger',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='httptrigger',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='http_triggers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduletrigger',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scheduletrigger',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_triggers', to=settings.AUTH_USER_MODEL),
        ),
    ]
