# Generated by Django 5.2.13 on 2026-05-24 06:09

import django.db.models.deletion
import uuid
import vault.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('gemini', 'Gemini'), ('groq', 'Groq'), ('openrouter', 'OpenRouter'), ('anthropic', 'Anthropic'), ('openai', 'OpenAI'), ('azure_openai', 'Azure OpenAI'), ('custom', 'Custom (LiteLLM-compatible)')], max_length=32)),
                ('api_key', vault.fields.EncryptedCharField(max_length=1024)),
                ('model_name', models.CharField(max_length=255)),
                ('api_version', models.CharField(blank=True, max_length=64)),
                ('base_url', models.URLField(blank=True, max_length=512)),
                ('system_instruction', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LLM Configuration',
                'verbose_name_plural': 'LLM Configurations',
                'db_table': 'llm_configs',
                'ordering': ['-modified_at'],
                'indexes': [models.Index(fields=['user', 'is_default'], name='llm_configs_user_id_29ab28_idx')],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
