# Generated by Django 5.2.13 on 2026-05-24 06:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autobot_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool')], max_length=16)),
                ('content', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('text/plain', 'Text'), ('text/markdown', 'Markdown')], default='text/markdown', max_length=32)),
                ('provider', models.CharField(blank=True, max_length=32)),
                ('model_name', models.CharField(blank=True, max_length=255)),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('completion_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('total_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('tool_calls', models.JSONField(blank=True, default=list)),
                ('tool_call_id', models.CharField(blank=True, max_length=128)),
                ('client_id', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Autobot Message',
                'verbose_name_plural': 'Autobot Messages',
                'db_table': 'autobot_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('system_prompt_override', models.TextField(blank=True, max_length=8000)),
                ('is_archived', models.BooleanField(default=False)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('llm_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='autobot_api.llmconfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autobot_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Autobot Thread',
                'verbose_name_plural': 'Autobot Threads',
                'db_table': 'autobot_threads',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary_text', models.TextField()),
                ('summary_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('up_to_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='autobot_api.message')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='autobot_api.thread')),
            ],
            options={
                'verbose_name': 'Autobot Summary',
                'verbose_name_plural': 'Autobot Summaries',
                'db_table': 'autobot_summaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='autobot_api.thread'),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tone', models.CharField(choices=[('concise', 'Concise'), ('balanced', 'Balanced'), ('detailed', 'Detailed')], default='balanced', max_length=16)),
                ('expertise', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='intermediate', max_length=16)),
                ('language', models.CharField(default='en', max_length=16)),
                ('custom_instructions', models.TextField(blank=True, max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('default_llm_config', models.ForeignKey(blank=True, help_text="User's preferred BYO config. If None, Autobot falls back to admin defaults configured in autobot.env.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='autobot_api.llmconfig')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autobot_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Autobot User Settings',
                'verbose_name_plural': 'Autobot User Settings',
                'db_table': 'autobot_user_settings',
            },
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['user', '-last_message_at'], name='autobot_thr_user_id_9b28fe_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['user', 'is_archived'], name='autobot_thr_user_id_96d99f_idx'),
        ),
        migrations.AddIndex(
            model_name='summary',
            index=models.Index(fields=['thread', '-created_at'], name='autobot_sum_thread__6224b7_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread', 'created_at'], name='autobot_mes_thread__d063fe_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread', 'role'], name='autobot_mes_thread__913eb9_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('client_id', ''), _negated=True), fields=('thread', 'client_id'), name='unique_autobot_message_client_id_per_thread'),
        ),
    ]
