# Generated by Django 5.2.13 on 2026-06-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autobot_api', '0002_message_thread_summary_message_thread_usersettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_byo',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
