# Generated by Django 5.2.13 on 2026-06-20 12:41

import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autobot_api', '0004_enable_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('docs', 'Docs'), ('tutorials', 'Tutorials')], max_length=16)),
                ('doc_path', models.CharField(max_length=512)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('url', models.CharField(blank=True, max_length=1024)),
                ('heading_path', models.CharField(blank=True, max_length=1024)),
                ('content', models.TextField()),
                ('content_hash', models.CharField(max_length=64)),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('token_count', models.PositiveIntegerField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documentation Chunk',
                'verbose_name_plural': 'Documentation Chunks',
                'db_table': 'autobot_doc_chunks',
                'ordering': ['source', 'doc_path', 'chunk_index'],
                'indexes': [models.Index(fields=['source', 'doc_path'], name='autobot_doc_source_dc1155_idx'), pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='doc_chunk_embedding_hnsw', opclasses=['vector_cosine_ops'])],
                'constraints': [models.UniqueConstraint(fields=('source', 'doc_path', 'chunk_index'), name='unique_doc_chunk_slot')],
            },
        ),
    ]
