# Generated by Django 6.0 on 2026-01-21 04:41

import vault.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='cert_pem',
            field=vault.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='key_passphrase',
            field=vault.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='credential_type',
            field=models.CharField(choices=[('username_password', 'Username/Password'), ('ssh_key', 'SSH Key'), ('certificate', 'Certificate')], max_length=50),
        ),
        migrations.AlterField(
            model_name='credential',
            name='password',
            field=vault.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='ssh_key',
            field=vault.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
