# Generated by Django 6.0 on 2026-01-22 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_credential_cert_pem_credential_key_passphrase_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaults', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vault',
                'verbose_name_plural': 'Vaults',
                'db_table': 'vaults',
                'ordering': ['-modified_at'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='credential',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='server',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='credential',
            name='vault',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='vault.vault'),
        ),
        migrations.AddField(
            model_name='server',
            name='vault',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='vault.vault'),
        ),
        migrations.AlterUniqueTogether(
            name='credential',
            unique_together={('vault', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='server',
            unique_together={('vault', 'name')},
        ),
        migrations.RemoveField(
            model_name='credential',
            name='user',
        ),
        migrations.RemoveField(
            model_name='server',
            name='user',
        ),
    ]
