# Generated by Django 6.0 on 2026-01-22 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_vault_alter_credential_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='vault',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='vault.vault'),
        ),
        migrations.AlterField(
            model_name='server',
            name='vault',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='vault.vault'),
        ),
    ]
