# Generated by Django 6.0 on 2026-04-23 16:48

import vault.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0007_cleanup_uuid_transition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='key_passphrase',
            field=vault.fields.EncryptedCharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='password',
            field=vault.fields.EncryptedCharField(blank=True, max_length=1024, null=True),
        ),
    ]
