# Generated by Django 6.0 on 2026-01-15 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflow',
            options={'ordering': ['-modified_at'], 'verbose_name': 'Workflow', 'verbose_name_plural': 'Workflows'},
        ),
    ]
