# Generated by Django 6.0 on 2026-01-15 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_alter_workflow_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='workflow',
            table='workflows',
        ),
    ]
