# Generated by Django 6.0 on 2026-01-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_workflow_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
